# Generated by Django 5.1.5 on 2025-02-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0002_task_taskassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
