# Generated by Django 5.1.5 on 2025-01-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department_id',
            new_name='dept_id',
        ),
    ]
