# Generated by Django 5.1.5 on 2025-02-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_rename_employee_taskassignment_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='task',
            new_name='task_id',
        ),
    ]
